# Generated by Django 3.2.5 on 2021-08-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100)),
                ('deliveryboy', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
