# Generated by Django 3.2.5 on 2021-08-08 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boyname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('boystatus', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order',
            new_name='ordername',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='status',
            new_name='orderstatus',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
        migrations.AddField(
            model_name='orders',
            name='orderaddress',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='orders',
            name='deliveryboy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.boydetails'),
        ),
    ]
